export const WELCOME_EMAIL_TEMPLATE = '';
export const NEWS_SUMMARY_EMAIL_TEMPLATE = '';
export const STOCK_ALERT_UPPER_EMAIL_TEMPLATE = '';
export const STOCK_ALERT_LOWER_EMAIL_TEMPLATE = '';
export const VOLUME_ALERT_EMAIL_TEMPLATE = '';
export const INACTIVE_USER_REMINDER_EMAIL_TEMPLATE = '';
